### ISSUE TITLE
Organização do dataset.

### ISSUE THREAD

**Issue by Carloshtda** [tarcisiolf0/covid19_dl_project#2]
- [x] Extrair imagens DIACOM.
- [x] Padronizar o tamanho para 480x480.
- [x] Dividir em treinamento, validação e teste.

**Comment by tarcisiolf0** [comment]
A parte de padronização dos dados foi feito em etapa posterior. O código de organização do dataset está disponível em: https://github.com/tarcisiolf0/covid19_dl_project/blob/main/dataset_organization_final_version.ipynb
